"""empty message

Revision ID: dca6d8e2bdad
Revises: a30bf62352c2
Create Date: 2016-12-26 14:05:02.139424

"""

# revision identifiers, used by Alembic.
revision = 'dca6d8e2bdad'
down_revision = 'a30bf62352c2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('sms_enabled', sa.Boolean(), nullable=True))
    op.add_column('reminders', sa.Column('sms_number', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reminders', 'sms_number')
    op.drop_column('reminders', 'sms_enabled')
    # ### end Alembic commands ###
