"""empty message

Revision ID: ea36452f6db6
Revises: dca6d8e2bdad
Create Date: 2017-01-02 07:49:19.996363

"""

# revision identifiers, used by Alembic.
revision = 'ea36452f6db6'
down_revision = 'dca6d8e2bdad'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('timezone', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reminders', 'timezone')
    # ### end Alembic commands ###
